### ISSUE TITLE
Connections - persistence

### ISSUE THREAD

**Issue by raihanflores** [cashbit/sails-crudface#12]
Hi,
Does crudface support MySQL or MSSQL? I've been looking around for any settings that I can tweak but couldn't find one.. is the data being saved in memory?

Thanks,
Ryann

**Comment by Jogai** [comment]
Since its using Sails you can configure it according to the sails docs: http://sailsjs.org/#/documentation/reference/sails.config/sails.config.connections.html

For various databases is an adapter available: https://github.com/balderdashy/sails-docs/blob/0.9/Database-Support.md

There are community driven adapters for mssql, like this one: https://www.npmjs.org/package/sails-mssql

**Comment by raihanflores** [comment]
Wow reply is quick!! Yeah kinda figured it out that the model attributes must be the same as the crudconfig file. Is my observation correct? Anyways with a minimum/simple set of attributes we were able to save data to a mysql db.

Thanks!
Ryann
